name: profpilot
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: BMHANNAPro
      fonts:
        - asset: assets/fonts/BMHANNAProOTF.otf

    - family: AppleSDGothicNeo
      fonts:
        - asset: assets/fonts/Apple_SD_Gothic_Neo_Bold.otf